# Generated by Django 3.0.6 on 2020-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('mobiel', models.BooleanField()),
                ('afstand', models.IntegerField(help_text='in meters')),
            ],
            options={
                'verbose_name_plural': 'Banen',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duur', models.DurationField()),
                ('opstart_duur', models.DurationField()),
                ('afbouw_duur', models.DurationField()),
                ('open', models.TimeField()),
                ('sluit', models.TimeField()),
                ('prioriteit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Protocollen',
            },
        ),
    ]
