# Generated by Django 3.0.6 on 2020-05-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('eind', models.DateTimeField()),
                ('baan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserveringen.Baan')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserveringen.Protocol')),
            ],
        ),
    ]
