# Generated by Django 3.0.6 on 2020-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0006_auto_20200507_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baan',
            name='afstand',
        ),
        migrations.RemoveField(
            model_name='baan',
            name='mobiel',
        ),
        migrations.AddField(
            model_name='baan',
            name='label',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
