# Generated by Django 3.0.6 on 2020-05-15 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0007_auto_20200515_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baan',
            options={'ordering': ['naam'], 'verbose_name_plural': 'Banen'},
        ),
        migrations.AddField(
            model_name='schietdag',
            name='extra_tijd_begin',
            field=models.DurationField(default=datetime.timedelta(seconds=600), help_text='[HH:MM:SS] Als er tijd onverdeeld blijft door je slotkeuze, verdeel deze als extra aan het begin en eind'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schietdag',
            name='afbouw_duur',
            field=models.DurationField(help_text='[HH:MM:SS] Hoelang mogen deelnemers na het slot einde aanwezig zijn?'),
        ),
        migrations.AlterField(
            model_name='schietdag',
            name='opstart_duur',
            field=models.DurationField(help_text='[HH:MM:SS] Hoelang van te voren mogen deelnemers aanwezig zijn?'),
        ),
        migrations.AlterField(
            model_name='schietdag',
            name='slot_duur',
            field=models.DurationField(help_text='[HH:MM:SS] Overgebleven tijd zal worden toegevoegd aan het eerste en laatste slot.'),
        ),
    ]
