# Generated by Django 3.0.6 on 2020-05-17 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0010_reservering_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vereniging_naam', models.CharField(default='Eemschutters', max_length=255)),
                ('reserveer_venster', models.DurationField(default=datetime.timedelta(days=7), help_text='Hoelang van te voren mogen sloten gereserveerd worden?')),
                ('reserveringen_per_week', models.IntegerField(default=2, help_text='Hoeveel reserveringen per week mogen leden maken?')),
                ('sleutelhouder_slot', models.IntegerField(default=2, help_text='Op welk slot moeten een sleutehouders slot standaard gereserveerd worden? ')),
                ('nieuws_bericht', models.CharField(default='Welkom, hier staat het laatste nieuws.', help_text='Een nieuwsberichtje op de homepagina.', max_length=500)),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
                ('sleutelhouder_baan', models.ForeignKey(blank=True, default=None, help_text='Op welke baan moet een sleutelhouders slot standaard gereserveerd worden?', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='reserveringen.Baan')),
            ],
            options={
                'verbose_name': 'Instellingen',
            },
        ),
    ]
