# Generated by Django 3.0.6 on 2020-05-17 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0012_auto_20200517_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='reserveer_venster',
            field=models.DurationField(default=datetime.timedelta(days=7), help_text='Hoelang van te voren mogen sloten gereserveerd worden?'),
        ),
    ]
