# Generated by Django 3.0.6 on 2020-05-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0013_auto_20200517_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='reserveringen_per_week',
            field=models.IntegerField(default=2, help_text='Hoeveel reserveringen per week mogen leden maken? (eerste slot = 0)'),
        ),
    ]
