# Generated by Django 3.0.6 on 2020-05-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0015_auto_20200517_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservering',
            name='baan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveringen.Baan'),
        ),
    ]
