# Generated by Django 3.0.6 on 2020-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0016_auto_20200519_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='NieuwsBericht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nieuws_bericht', models.CharField(default='Welkom, hier staat het laatste nieuws.', help_text='Een nieuwsberichtje op de homepagina.', max_length=500)),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='gewijzigd_op',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nieuws_bericht',
        ),
    ]
