# Generated by Django 3.0.6 on 2020-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0017_auto_20200519_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nieuwsbericht',
            options={'verbose_name': 'Nieuwsbericht', 'verbose_name_plural': 'Nieuwsberichten'},
        ),
        migrations.AlterField(
            model_name='nieuwsbericht',
            name='nieuws_bericht',
            field=models.TextField(default='Welkom, hier staat het laatste nieuws.', help_text='Een nieuwsberichtje op de homepagina.', max_length=800),
        ),
    ]
