# Generated by Django 3.0.6 on 2021-02-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0018_auto_20200519_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservering',
            name='schietdag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveringen.Schietdag'),
        ),
    ]
