# Generated by Django 3.0.6 on 2021-02-28 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0019_auto_20210228_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='reserveer_stop',
            field=models.DurationField(default=datetime.timedelta(days=24), help_text='Hoelang van te voren sluit de mogelijkheid tot reserveren?'),
        ),
    ]
