# Generated by Django 3.0.6 on 2021-02-28 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0020_siteconfiguration_reserveer_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='reserveer_stop',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Hoelang van te voren sluit de mogelijkheid tot reserveren?'),
        ),
    ]
