# Generated by Django 3.0.6 on 2020-05-07 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserveringen', '0002_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('eind', models.DateTimeField()),
                ('baan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserveringen.Baan')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserveringen.Protocol')),
            ],
            options={
                'verbose_name_plural': 'Reserveringen',
            },
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
