# Generated by Django 3.0.6 on 2020-05-07 16:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0003_auto_20200507_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='geldig_op',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Maandag'), ('1', 'Dinsdag'), ('2', 'Woensdag'), ('3', 'Donderdag'), ('4', 'Vrijdag'), ('5', 'Zaterdag'), ('6', 'Zondag')], default=None, max_length=13, null=True),
        ),
    ]
